/**
 * Typed accessor for the lazy-loaded capability verdict matrix.
 *
 * Provenance: generated by unified-trading-pm/scripts/openapi/generate_capability_manifest.py
 * Do NOT hand-edit — refresh by running the openapi sync script in unified-trading-pm.
 *
 * Bundle decision: at ~2.2 MB the matrix is too large for the Vite static bundle.
 * It is loaded on demand via dynamic import only when the Verdicts sub-tab is first
 * rendered.  The existing capability-manifest.json (938 KB) remains statically bundled.
 */

// ---------------------------------------------------------------------------
// Schema types (mirrors UAC openapi/capability-verdict-matrix.json)
// ---------------------------------------------------------------------------

export interface VerdictMatrixSummary {
  total_cells: number;
  available: number;
  blocked: number;
  not_registered: number;
}

export interface BlockedAlgo {
  algo: string;
  reason: string;
}

export interface VerdictCell {
  venue: string;
  instrument_type: string;
  leg_id?: string;
  leg_role?: string;
  instruction_action: string;
  available_algos: string[];
  blocked_algos: BlockedAlgo[];
}

/** A registered archetype with verdict detail. */
export interface VerdictArchetypeEntry {
  archetype: string;
  available_count: number;
  blocked_count: number;
  cell_count: number;
  instruction_actions: string[];
  valid_algos: string[];
  not_registered: false;
  cells: VerdictCell[];
}

/** An archetype that exists only as a theoretical/unregistered placeholder. */
export interface VerdictArchetypeNotRegistered {
  archetype: string;
  cell_count: 0;
  not_registered: true;
  reason: string;
  gap_type: "not_registered";
  not_registered_algos: string[];
}

export type VerdictArchetype = VerdictArchetypeEntry | VerdictArchetypeNotRegistered;

export interface VerdictMatrixAxes {
  archetype: string;
  venue: string;
  instrument_type: string;
  instruction_action: string;
  algo: string;
}

export interface CapabilityVerdictMatrix {
  matrix_version: string;
  generated_from_commit: string;
  summary: VerdictMatrixSummary;
  verdicts: string[];
  axes: VerdictMatrixAxes;
  archetypes: VerdictArchetype[];
}

// ---------------------------------------------------------------------------
// Lazy-load helper (dynamic import — not bundled at build time)
// ---------------------------------------------------------------------------

let _cached: CapabilityVerdictMatrix | null = null;

export async function loadVerdictMatrix(): Promise<CapabilityVerdictMatrix> {
  if (_cached) return _cached;
  const mod = await import("./capability-verdict-matrix.json");
  const matrix = mod.default as CapabilityVerdictMatrix;
  if (!matrix.summary || !Array.isArray(matrix.archetypes)) {
    throw new Error("capability-verdict-matrix.json: missing summary or archetypes");
  }
  _cached = matrix;
  return matrix;
}
