/**
 * Typed accessor for the static capability manifest.
 *
 * Provenance: generated by unified-trading-pm/scripts/openapi/generate_capability_manifest.py
 * Do NOT hand-edit — refresh by running the openapi sync script in unified-trading-pm.
 */
import rawManifest from "./capability-manifest.json";

// ---------------------------------------------------------------------------
// Schema types (mirrors unified_api_contracts.internal.capability_manifest)
// ---------------------------------------------------------------------------

export type NodeKind =
  | "archetype"
  | "broker"
  | "chain"
  | "collateral_policy"
  | "custody_provider"
  | "data_source"
  | "execution_algo"
  | "family"
  | "feature_group"
  | "fund_structure"
  | "gap_registry"
  | "instrument_type"
  | "kill_switch_reason"
  | "leg"
  | "ml_model"
  | "risk_gate_layer"
  | "signing_surface"
  | "venue"
  | "wallet";

export type EdgeStatus = "available" | "partial" | "not_available" | "not_registered";

export type GapType = "missing_registry" | "missing_extraction" | "needs_code_scan" | "logical_dead_end";

export type EdgeRelation =
  | "belongs_to_family"
  | "supports"
  | "trades_instrument"
  | "at_risk_layer"
  | "supports_mode:batch"
  | "supports_mode:live"
  | "supports_mode:replay"
  | "over_transport:rest"
  | "over_transport:flat_file"
  | "over_transport:websocket"
  | "on_chain"
  | "registry_gap"
  | "routed_via"
  | "wallet_split_policy"
  | "min_data_to_run"
  | "has_leg"
  | "uses_algo"
  | "accepts_collateral"
  | (string & Record<never, never>); // allow future relations without breaking

export interface CapabilityNode {
  kind: NodeKind;
  node_id: string;
  label: string;
  metadata: Record<string, string>;
}

export interface CapabilityEdge {
  from_node_id: string;
  to_node_id: string;
  relation: EdgeRelation;
  status: EdgeStatus;
  gap_type: GapType | null;
  reason: string | null;
  readiness: string | null;
  agent_annotation: string | null;
}

export interface CapabilityGaps {
  annotation_orphans?: number;
  broker_classed_venues?: number;
  logical_dead_end: number;
  logical_dead_ends: number;
  missing_extraction: number;
  missing_registry: number;
  needs_code_scan: number;
  not_registered_total: number;
  orphan_nodes: number;
  unbuilt_dead_ends: number;
}

export interface CapabilityManifest {
  manifest_version: string;
  generated_from_commit: string;
  nodes: CapabilityNode[];
  edges: CapabilityEdge[];
  gaps: CapabilityGaps;
}

// ---------------------------------------------------------------------------
// Load + validate at import time (fast — JSON bundled by Vite)
// ---------------------------------------------------------------------------

function loadManifest(): CapabilityManifest {
  const m = rawManifest as CapabilityManifest;
  if (!Array.isArray(m.nodes) || !Array.isArray(m.edges)) {
    throw new Error("capability-manifest.json: missing nodes or edges array");
  }
  return m;
}

export const capabilityManifest: CapabilityManifest = loadManifest();
